spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}   # Tự động lấy từ .env
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    banner-mode: off

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    isSSL: false

server:
  servlet:
    session:
      timeout: 1800s

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET}
    jwtCookieName: ${JWT_COOKIE_NAME}
    expiration: ${JWT_EXPIRATION}

storage:
  location: ${STORAGE_LOCATION:upload-dir}
  max-file-size: ${STORAGE_MAX_FILE_SIZE:10}
  max-request-size: ${STORAGE_MAX_REQUEST_SIZE:10}
  allowed-extensions: ${STORAGE_ALLOWED_EXTENSIONS:jpg,jpeg,png,gif,pdf,doc,docx}
